# snapcraft.yaml - builds a Snap package of OpenJDK
# Copyright (C) 2020-2021 John Neffenger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: openjdk
title: OpenJDK
summary: Current JDK release and early-access builds
description: |
  OpenJDK is the official reference implementation of the Java
  Platform, Standard Edition, a cross-platform computing environment
  that lets you develop and deploy Java applications on desktops,
  servers, and embedded systems.

  This package provides everything you need to develop a Java
  application on Linux, including all of the latest development tools,
  class libraries, API documentation, and source code of the Java
  Development Kit (JDK).

  To get started, see the README file for this package on GitHub:

  https://github.com/jgneff/openjdk

  Java and OpenJDK are trademarks or registered trademarks of Oracle
  and/or its affiliates.

# When the JDK release or build number changes, update the following:
#   version, slots, parts.jdk.build-environment.BUILD_NUM
version: '17+35'
license: (GPL-2.0 WITH Classpath-exception-2.0)

base: core18
grade: stable
confinement: strict

architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf
- build-on: i386
- build-on: ppc64el
- build-on: s390x

slots:
  jdk-17-1804:
    interface: content
    read: [$SNAP/jdk]

plugs:
  home: null

apps:
  openjdk:
    command: bin/openjdk.sh
    environment:
      LC_ALL: C.UTF-8
  java:
    command: jdk/bin/java
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - x11
    environment:
      LC_ALL: C.UTF-8
  javac:
    command: jdk/bin/javac
    environment:
      LC_ALL: C.UTF-8
  javadoc:
    command: jdk/bin/javadoc
    environment:
      LC_ALL: C.UTF-8
  jar:
    command: jdk/bin/jar
    environment:
      LC_ALL: C.UTF-8
  jarsigner:
    command: jdk/bin/jarsigner
    environment:
      LC_ALL: C.UTF-8
  jlink:
    command: jdk/bin/jlink
    environment:
      LC_ALL: C.UTF-8
  jpackage:
    command: jdk/bin/jpackage
    environment:
      LC_ALL: C.UTF-8

parts:
  bin:
    plugin: dump
    source: .
    source-type: local
    stage: [bin]

  jdk:
    plugin: autotools
    source: https://github.com/openjdk/jdk17.git
    source-branch: jdk-$SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    build-snaps:
    - openjdk/latest/candidate
    build-packages:
    - libasound2-dev
    - libcups2-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libx11-dev
    - libxext-dev
    - libxrandr-dev
    - libxrender-dev
    - libxt-dev
    - libxtst-dev
    - unzip
    - zip
    build-environment:
    - JAVA_HOME: /snap/openjdk/current/jdk
    - BUILD_NUM: '35'
    # Option '--disable-warnings-as-errors' for armhf
    override-build: |
      set -o xtrace
      bash configure --enable-warnings-as-errors=no \
        --enable-javac-server=no \
        --with-version-pre=no \
        --with-version-opt=snap \
        --with-version-build=$BUILD_NUM \
        --with-source-date=version \
        --with-native-debug-symbols=none
      make images docs
      cd build/linux-*-server-release/images
      mv jdk docs $SNAPCRAFT_PART_INSTALL
    organize:
      docs: jdk/docs
    stage-packages:
    - binutils
    - dpkg
    - fakeroot
    - libasound2
    - libfreetype6
    - libpng16-16
    - libx11-6
    - libxau6
    - libxcb1
    - libxdmcp6
    - libxext6
    - libxi6
    - libxrender1
    - libxtst6
    - libfontconfig1

  del:
    after: [jdk]
    plugin: nil
    # Deletes files and links already available in the base snap
    override-prime: |
      set -o xtrace
      cd $SNAPCRAFT_PRIME
      base=/snap/core18/current
      list="etc lib* usr/lib usr/share"
      find $list -type f -exec test -f "$base/{}" \; -delete
      find $list -type l -exec test -L "$base/{}" \; -delete
      find * -type d -empty -exec test -d "$base/{}" \; -delete

layout:
  # Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
  /etc/fonts:
    bind: $SNAP/etc/fonts
  # dpkg: error: error opening configuration directory
  #     '/etc/dpkg/dpkg.cfg.d': Permission denied
  /etc/dpkg:
    bind: $SNAP/etc/dpkg
  # Can not find fakeroot. Reason: Cannot run program "fakeroot":
  #     error=2, No such file or directory
  /usr/bin/fakeroot:
    symlink: $SNAP/usr/bin/fakeroot-sysv
  # fakeroot: preload library `libfakeroot-sysv.so' not found, aborting.
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libfakeroot/libfakeroot-sysv.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libfakeroot/libfakeroot-sysv.so
  # /usr/bin/fakeroot: 1: eval: /usr/bin/faked-sysv: not found
  /usr/bin/faked-sysv:
    symlink: $SNAP/usr/bin/faked-sysv
